config/routes.rb
Rails.application.routes.draw do

  resource :registrations, only: [:new, :create]
  resource :sessions, only: [:new, :create, :destroy]

  root to: 'registrations#new'

  resources :articles do
    resources :cheers
    resources :completions
    resources :comments
  end

  get "tweet/input"
  post "tweet/update"
  get "/auth/:provider/callback" => "sessions#callback"
  get "/signout" => "sessions#remove"

  resources :users

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  has_many :cheers
  has_many :completions
  has_many :comments

  def cheered_by?(user)
    cheers.where(user_id: user.id).exists?
  end
  def completed_by?(user)
    completions.where(user_id: user.id).exists?
  end
  default_scope -> { order(created_at: :desc)}
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :require_login, except: [:index]
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
    @users = User.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if signed_in?
      client = Twitter::REST::Client.new do |config|
        config.consumer_key         = "Qndxjz83ZuZHwm7LoN9VX0wzC"
        config.consumer_secret      = "BmrtnW4g97au2Zn3TFPZKH09oyZjFOIOCmco0j7PY5JUikk43e"
        config.access_token         = session[:oauth_token]
        config.access_token_secret  = session[:oauth_token_secret]
      end
      client.update("Zangeをして、Chigiriを結びました。zange.co #zange")
    end

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Zangeが投稿されました。' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Zangeが変更されました。' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Zangeが消去されました。' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :content, :category, :solution, :deadline)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.haml
= form_for @article do |f|
  - if @article.errors.any?
    #error_explanation
      %h2= "#{pluralize(@article.errors.count, "error")} prohibited this article from being saved:"
      %ul
        - @article.errors.full_messages.each do |msg|
          %li= msg

  -# .field
  -#   = f.label :user_id
  -#   = f.number_field :user_id
  .field
    = f.label :title, "懺悔したいあやまちにタイトルをつけてください。（30字以内）", class: "control-label"
    %div
      = f.text_field :title, class: "form-control"
  .field
    = f.label :content, "懺悔したいあやまちの内容を書いてください。", class: "control-label"
    %div
      = f.text_area :content, class: "form-control zange-form-content"
  .field
    = f.label :category, "懺悔のジャンル/シチュエーションを選んでください。", class: "control-label"
    %div
      = f.select :category do
        - [['仕事', "work"], ['学校', "school"], ['恋愛', "love"], ['家族', "family"], ['友人', "friend"], ['自分自身', "self"]].each do |c|
          = content_tag(:option, c.first, value: c.last)
  .field
    = f.label :solution, "今後、Chigiriとしてどんな対策や行動を約束しますか？毎日できることを書いてください。", class: "control-label"
    %div
      = f.text_field :solution, class: "form-control"
  .field
    = f.label :deadline, "そのChigiriをいつまでつづけますか？", class: "control-label"
    %div
      = f.datetime_select :deadline, :discard_hour => true, :discard_mitute => true, :use_month_names => %w(1月 2月 3月 4月 5月 6月 7月 8月 9月 10月 11月 12月), class: "form-control"
  -if signed_in?
    %p
      twitterと連携しています。
      %br
        Zangeを投稿すると、自動的にtweetが送信されて、より強いchigiriを結べます。
        %br
          ※Zangeの投稿の内容はtweetされませんので、ご安心ください。
  -else
    %p
      twitterとアカウントを連携すると、より強いchigiriを結べます。
    %p
      =link_to "twitterと連携する場合はこちら", edit_user_path(current_user)
  .actions.center
    = f.submit "決意する", class: "red-btn"

app/views/articles/edit.html.haml
#contents
  #new-zange
    .forms
      = render 'form'

      = link_to 'Back', articles_path

app/views/articles/index.html.haml
#contents
  #timeline
    .timeline-header
      - if logged_in?
        %ul
          .float-left.table
            %li.media-theme.table-cell.middle.active
              みんなのZangeとChigiri
            =link_to current_user do
              %li.media-theme.table-cell.middle
                #{current_user.name}のZangeとChigiri
          .float-right.table
            .table-cell.middle
              = link_to new_article_path do
                .red-btn
                  .media-new-zange.center
                    Zangeする
        .clear
    .timeline-items
      = div_for @articles, class: "timeline-item" do |article|
        .media.table
          .media-name.center
            - if logged_in?
              = link_to article.user.name, user_path(article.user)
            - else
              = link_to article.user.name, root_url
          .media-body.middle
            .media-body-zange
              .media-category
                =image_tag("sorry.png")
                Zange
              %p= article.title
            .media-body-chigiri
              .media-category
                =image_tag("promise.png")
                Chigiri
              %p= article.solution
          - if logged_in?
            .media-bottom
              .media-next.center
                =link_to '続きを読む', article
              =link_to article_cheers_path(article), method: :post do
                .red-btn.float-left
                  .media-cheer
                    %i.fa.fa-bullhorn
                      応援する!
              .media-nums.float-right
                %i.fa.fa-bullhorn.float-left
                  = article.cheers.length
                %i.fa.fa-check-square.float-left
                  = article.completions.length
                %i.fa.fa-comment-o.float-left
                  = article.comments.length
            .clear
          - else
            .media-bottom
              .media-next.center
                =link_to "無料登録して続きを読む", root_url
              .media-nums.float-right
                %i.fa.fa-bullhorn.float-left
                  = article.cheers.length
                %i.fa.fa-check-square.float-left
                  = article.completions.length
                %i.fa.fa-comment-o.float-left
                  = article.comments.length





    

app/views/articles/new.html.haml
#contents
	#new-zange
		.forms
			= render 'form'

			= link_to '戻る', articles_path

app/views/articles/show.html.haml
%p#notice= notice

#contents
  #zange-detail
    .detail-header
      - if logged_in?
        %ul.table
          %li.media-theme.float-left
            #{@article.user.name} のzangeとchigiri
          %li.float-right
            .btn-word
            = link_to '編集する', edit_article_path(@article)
          .clear

    .detail-item
      .media
        .media-category
          =image_tag("sorry.png")
          Zange
        .media-title
          %p= @article.title
        .media-category
          %p 
            カテゴリ:
            = @article.category
        .media-content
          %p
            = raw hbr(@article.content)
        .media-category
          =image_tag("promise.png")
          Chigiri
        .media-content
          %p
            = @article.solution
        .media-date
          %p
            = @article.deadline
            までのchigiri
        .media-btn
          - if current_user.id == @article.user_id
            =link_to article_completions_path(@article), method: :post do
              .red-btn.float-left
                .media-done
                  %i.fa.fa-check-square
                    できた！
          - else
            =link_to article_cheers_path(@article), method: :post do
              .red-btn.float-left
                .media-cheer
                  %i.fa.fa-bullhorn
                    応援する!
        .media-nums.float-right
          %i.fa.fa-bullhorn.float-left
            = @article.cheers.length
          %i.fa.fa-check-square.float-left
            = @article.completions.length
          %i.fa.fa-comment-o.float-left
            = @article.comments.length
    = link_to articles_path do
      .media-back
        戻る


  #comments
    .comments-header
      応援や共感のコメント一覧
    .comments-wrapper
      - if @article.comments.empty?
        .comment
          まだコメントはありません。
      - @article.comments.each do |comment|
        .comment
          .comment-user
            name:
            = comment.user.name
          .comment-content
            = comment.content
    .comment-form
      = form_for ([@article, @article.comments.build]) do |f|
        .field
          = f.label :content, "応援や共感をコメントしてあげよう！"
        .field
          = current_user.name
          = f.text_area :content, class: "form-control"
        .actions.center
          = f.submit 'コメントする', class: "comment-submit"