config/routes.rb
Rails.application.routes.draw do

  resource :registrations, only: [:new, :create]
  resource :sessions, only: [:new, :create, :destroy]

  root to: 'registrations#new'

  resources :articles do
    resources :cheers
    resources :completions
    resources :comments
  end

  get "tweet/input"
  post "tweet/update"
  get "/auth/:provider/callback" => "sessions#callback"
  get "/signout" => "sessions#remove"

  resources :users

end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  has_many :articles, dependent: :destroy
  has_many :cheers, dependent: :destroy
  has_many :completions, dependent: :destroy
  has_many :comments

  validates :name, length: { maximum: 140 }
  validates :bio, length: { maximum: 200 }
  validates :email, presence: true, uniqueness: { case_sentensive: false }
  validates :password, confirmation: true, length: { in: 4..24}, if: :password
  validates :password_confirmation, presence: true, if: :password
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :bio)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name, "ユーザーネーム", class: "form-label"
    = f.text_field :name
  .field
    = f.label :email
    = f.text_field :email
  .actions
    = f.submit '変更する', class: "red-btn"

app/views/users/edit.html.haml
#contents
  #edit
    %h3
      設定

    = render 'form'
    -if signed_in?
      %p
        現在、twitterとアカウントを連携しています。
        %br
          ※Zangeを投稿すると、自動的にtweetが送信されます。
      %p
        連携を外す場合は、
        =link_to "こちら", "/signout"
    -else
      %p
        現在、twitterとアカウントを連携していません。
      %p
        twitterと連携する場合は、下のボタンをクリック！
      %p.red-btn.center.middle
        =link_to "twitterと連携", "/auth/twitter"
    .red-btn.middle.center
      = link_to 'mypageへ', @user

app/views/users/index.html.haml
%h1 Listing users

%table
  %thead
    %tr
      %th Name
      %th Email
      %th Bio
      %th
      %th
      %th

  %tbody
    - @users.each do |user|
      %tr
        %td= user.name
        %td= user.email
        %td= user.bio
        %td= link_to 'Show', user
        %td= link_to 'Edit', edit_user_path(user)
        %td= link_to 'Destroy', user, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New User', new_user_path

app/views/users/new.html.haml
%h1 New user

= render 'form'

= link_to 'Back', users_path

app/views/users/show.html.haml
#contents
  #my-timeline
    .my-timeline-header
      - if logged_in?
        %ul
          .float-left.table
            = link_to articles_path do
              %li.media-theme.table-cell.middle
                みんなのZangeとChigiri
            %li.media-theme.table-cell.middle.active
              #{current_user.name} のZangeとChigiri
          - unless signed_in?
            .float-right.table
              .table-cell.middle
                = link_to "/auth/twitter" do
                  .red-btn
                    .media-new-zange.center
                      twitterと連携
          - if current_user.id == @user.id
            .float-right.table
              .table-cell.middle
                = link_to new_article_path do
                  .red-btn
                    .media-new-zange.center
                      Zangeする
        .clear

    .my-timeline-items
      = div_for @user.articles, class: "my-timeline-item" do |article|
        .media.table
          .media-name.center
            = link_to article.user.name, user_path(article.user)
          .media-body.middle
            .media-body-zange
              .media-category
                =image_tag("sorry.png")
                Zange                
              %p= article.title
            .media-body-chigiri
              .media-category
                =image_tag("promise.png")
                Chigiri
              %p= article.solution
          .media-bottom
            .media-next.center
              =link_to '続きを読む', article
            - if current_user.id == @user.id
              =link_to article_completions_path(article), method: :post do
                .red-btn.float-left
                  .media-done
                    %i.fa.fa-check-square
                      できた！
            - else
              =link_to article_cheers_path(article), method: :post do
                .red-btn.float-left
                  .media-cheer
                    %i.fa.fa-bullhorn
                      応援する!
            .media-nums.float-right
              %i.fa.fa-bullhorn.float-left
                = article.cheers.length
              %i.fa.fa-check-square.float-left
                = article.completions.length
              %i.fa.fa-comment-o.float-left
                = article.comments.length
          .clear