config/routes.rb
Rails.application.routes.draw do

  resource :registrations, only: [:new, :create]
  resource :sessions, only: [:new, :create, :destroy]

  root to: 'registrations#new'

  resources :articles do
    resources :cheers
    resources :completions
    resources :comments
  end

  get "tweet/input"
  post "tweet/update"
  get "/auth/:provider/callback" => "sessions#callback"
  get "/signout" => "sessions#remove"

  resources :users

end

app/models/cheer.rb
class Cheer < ActiveRecord::Base
  belongs_to :articles
  belongs_to :users
end

app/controllers/cheers_controller.rb
class CheersController < ApplicationController
  before_action :set_cheer, only: [:show, :edit, :update, :destroy]

  # GET /cheers
  # GET /cheers.json
  def index
    @cheers = Cheer.all
  end

  # GET /cheers/1
  # GET /cheers/1.json
  def show
  end

  # GET /cheers/new
  def new
    @cheer = Cheer.new
  end

  # GET /cheers/1/edit
  def edit
  end

  # POST /cheers
  # POST /cheers.json
  def create
    @article = Article.find(params[:article_id])
    @cheer = Cheer.new(user_id: current_user.id, article_id: @article.id)

    respond_to do |format|
      if @cheer.save
        format.html { redirect_to :back }
        format.json { render :show, status: :created, location: @cheer }
      else
        format.html { render :new }
        format.json { render json: @cheer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cheers/1
  # PATCH/PUT /cheers/1.json
  def update
    respond_to do |format|
      if @cheer.update(cheer_params)
        format.html { redirect_to @cheer, notice: 'Cheer was successfully updated.' }
        format.json { render :show, status: :ok, location: @cheer }
      else
        format.html { render :edit }
        format.json { render json: @cheer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cheers/1
  # DELETE /cheers/1.json
  def destroy
    @cheer.destroy
    respond_to do |format|
      format.html { redirect_to cheers_url, notice: 'Cheer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cheer
      @cheer = Cheer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cheer_params
      params.require(:cheer).permit(:user_id, :article_id)
    end
end

app/helpers/cheers_helper.rb
module CheersHelper
end

app/views/cheers/_form.html.haml
= form_for @cheer do |f|
  - if @cheer.errors.any?
    #error_explanation
      %h2= "#{pluralize(@cheer.errors.count, "error")} prohibited this cheer from being saved:"
      %ul
        - @cheer.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :user_id
    = f.number_field :user_id
  .field
    = f.label :article_id
    = f.number_field :article_id
  .actions
    = f.submit 'Save'

app/views/cheers/edit.html.haml
%h1 Editing cheer

= render 'form'

= link_to 'Show', @cheer
\|
= link_to 'Back', cheers_path

app/views/cheers/index.html.haml
%h1 Listing cheers

%table
  %thead
    %tr
      %th User
      %th Article
      %th
      %th
      %th

  %tbody
    - @cheers.each do |cheer|
      %tr
        %td= cheer.user_id
        %td= cheer.article_id
        %td= link_to 'Show', cheer
        %td= link_to 'Edit', edit_cheer_path(cheer)
        %td= link_to 'Destroy', cheer, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Cheer', new_cheer_path

app/views/cheers/new.html.haml
%h1 New cheer

= render 'form'

= link_to 'Back', cheers_path

app/views/cheers/show.html.haml
%p#notice= notice

%p
  %b User:
  = @cheer.user_id
%p
  %b Article:
  = @cheer.article_id

= link_to 'Edit', edit_cheer_path(@cheer)
\|
= link_to 'Back', cheers_path