config/routes.rb
Rails.application.routes.draw do

  resource :registrations, only: [:new, :create]
  resource :sessions, only: [:new, :create, :destroy]

  root to: 'registrations#new'

  resources :articles do
    resources :cheers
    resources :completions
    resources :comments
  end

  get "tweet/input"
  post "tweet/update"
  get "/auth/:provider/callback" => "sessions#callback"
  get "/signout" => "sessions#remove"

  resources :users

end

app/models/completion.rb
class Completion < ActiveRecord::Base
  belongs_to :user
  belongs_to :article
end

app/controllers/completions_controller.rb
class CompletionsController < ApplicationController
  before_action :set_completion, only: [:show, :edit, :update, :destroy]

  # GET /completions
  # GET /completions.json
  def index
    @completions = Completion.all
  end

  # GET /completions/1
  # GET /completions/1.json
  def show
  end

  # GET /completions/new
  def new
    @completion = Completion.new
  end

  # GET /completions/1/edit
  def edit
  end

  # POST /completions
  # POST /completions.json
  def create
    @article = Article.find(params[:article_id])
    @completion = Completion.new(article_id: @article.id)

    respond_to do |format|
      if @completion.save
        format.html { redirect_to :back, notice: '明日からもがんばりましょう。' }
        format.json { render :show, status: :created, location: @completion }
      else
        format.html { render :new }
        format.json { render json: @completion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /completions/1
  # PATCH/PUT /completions/1.json
  def update
    respond_to do |format|
      if @completion.update(completion_params)
        format.html { redirect_to @completion, notice: 'Completion was successfully updated.' }
        format.json { render :show, status: :ok, location: @completion }
      else
        format.html { render :edit }
        format.json { render json: @completion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /completions/1
  # DELETE /completions/1.json
  def destroy
    @completion.destroy
    respond_to do |format|
      format.html { redirect_to completions_url, notice: 'Completion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_completion
      @completion = Completion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def completion_params
      params.require(:completion).permit(:article_id)
    end
end

app/helpers/completions_helper.rb
module CompletionsHelper
end

app/views/completions/_form.html.haml
= form_for @completion do |f|
  - if @completion.errors.any?
    #error_explanation
      %h2= "#{pluralize(@completion.errors.count, "error")} prohibited this completion from being saved:"
      %ul
        - @completion.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :article_id
    = f.number_field :article_id
  .actions
    = f.submit 'Save'

app/views/completions/edit.html.haml
%h1 Editing completion

= render 'form'

= link_to 'Show', @completion
\|
= link_to 'Back', completions_path

app/views/completions/index.html.haml
%h1 Listing completions

%table
  %thead
    %tr
      %th Article
      %th
      %th
      %th

  %tbody
    - @completions.each do |completion|
      %tr
        %td= completion.article_id
        %td= link_to 'Show', completion
        %td= link_to 'Edit', edit_completion_path(completion)
        %td= link_to 'Destroy', completion, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Completion', new_completion_path

app/views/completions/new.html.haml
%h1 New completion

= render 'form'

= link_to 'Back', completions_path

app/views/completions/show.html.haml
%p#notice= notice

%p
  %b Article:
  = @completion.article_id

= link_to 'Edit', edit_completion_path(@completion)
\|
= link_to 'Back', completions_path